config/routes.rb
Pigecontrol::Application.routes.draw do
  resources :sources do |source|
    resources :chunks
    resources :labels do
      member { get :select }
    end
    resources :records
  end

  resource :label_selection, :controller => :label_selection
  resources :uploads do
    member { put :cancel }
  end

  root :to => "welcome#index"
end

app/models/label_selection.rb
class LabelSelection
  include Enumerable

  attr_reader :labels
  protected :labels

  def initialize(label_identifiers = [])
    @labels =
      unless label_identifiers.blank?
        Label.find label_identifiers
      else
        []
      end
  end

  def each(&block)
    @labels.each(&block)
  end

  def ==(other)
    other and @labels == other.to_a
  end

  def add(label)
    @labels.clear if source and source != label.source
    @labels = [ label, *labels ].uniq.sort_by(&:timestamp).last(2)
    notify_on_change
  end
  alias_method :<<, :add

  def completed?
    labels.size == 2
  end

  delegate :empty?, :to => :labels

  def chunk
    unless empty?
      source.chunks.build :begin => labels.first.timestamp, :end => labels.last.timestamp
    end
  end

  def clear
    labels.clear
    notify_on_change
  end

  def source
    if label = labels.first
      label.source
    end
  end

  def same_source?(other)
    return false unless source and other

    other_source = other.respond_to?(:source) ? other.source : other
    source == other_source
  end

  def same_time_range?(other)
    return false unless time_range and other

    other_time_range = other.respond_to?(:time_range) ? other.time_range : other
    [:begin, :end].all? do |attribute|
      (time_range.send(attribute) - other_time_range.send(attribute)).abs < 1
    end
  end

  def on_change(&block)
    @on_change_handler = block
    self
  end

  def notify_on_change
    @on_change_handler.call labels if @on_change_handler
  end

  def begin
    labels.first
  end

  def end
    labels.last
  end

  def time_range
    if completed?
      Range.new(self.begin.timestamp, self.end.timestamp)
    end
  end

  def can_begin?(label)
    not completed? and
      (empty? or labels.first.timestamp > label.timestamp)
  end

  def can_end?(label)
    not completed? and
      (empty? or labels.first.timestamp < label.timestamp)
  end

  extend ActiveModel::Naming
  include ActiveModel::Conversion

  def persisted?
    false
  end

end

app/controllers/label_selection_controller.rb
class LabelSelectionController < ApplicationController

  def destroy
    user_session.label_selection.clear
    redirect_to :back
  end

end

app/helpers/label_selection_helper.rb
module LabelSelectionHelper

  def class_for_label_in_selection(label_selection, label)
    case label
    when label_selection.begin
      "begin"
    when label_selection.end
      "end"
    end
  end

end

app/views/label_selections/_label_selection.erb
<%= render :partial => 'label_selections/label_selection_inline_help' %>

<% unless label_selection.empty? %>
<%= div_for label_selection do %>
<ul>
  <% for label in label_selection %>
  <li class="<%= class_for_label_in_selection(label_selection, label) %>">
    <%= link_to label.timestamp.strftime("%H:%M:%S"), source_label_path(label.source, label), :class => "timestamp" %>
    <%= link_to truncate(label.name, :length => 40), source_label_path(label.source, label) %>
  </li>
  <% end %>
</ul>

<div class="actions">
  <%= link_to t("label_selection.actions.create_chunk"), new_source_chunk_path(label_selection.source), :title => t("label_selection.actions.create_chunk_title"), :class => "create" %>
  <%= link_to t("label_selection.actions.destroy"), label_selection_path, :method => :delete, :title => t("label_selection.actions.destroy_title"), :class => "destroy" %>
</div>
<% end %>
<% end -%>

app/views/label_selections/_label_selection_inline_help.en.erb
<p>
  By selecting <%= link_to_unless current_page?(source_labels_path(Source.default)), "2 labels", source_labels_path(Source.default) %>, you can create a chunk in few clicks.
</p>

app/views/label_selections/_label_selection_inline_help.fr.erb
<p>
  En sélectionnant <%= link_to_unless current_page?(source_labels_path(Source.default)), "2 repères", source_labels_path(Source.default) %>, vous pouvez créer un extrait en quelques clics.
</p>