config/routes.rb
Pigecontrol::Application.routes.draw do
  resources :sources do |source|
    resources :chunks
    resources :labels do
      member { get :select }
    end
    resources :records
  end

  resource :label_selection, :controller => :label_selection
  resources :uploads do
    member { put :cancel }
  end

  root :to => "welcome#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="fr">
  <head>
    <title>Tryphon PigeBox - <%= title %></title>

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <link rel="shortcut icon" href="/favicon.ico" />

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body class="<%= controller.controller_name %> <%= controller.action_name %>">
    <ul id="access">
      <li><a href="#content">Aller au contenu</a></li>
      <li><a href="#sidebar">Aller au menu</a></li>
    </ul>
    <hr/>
    <div id="header">
      <div>
        <ul id="menu">
          <li><%= link_to t(".dashboard"), source_chunks_path(Source.default) %></li>
          <li><a href="#"><%= t(".help") %></a></li>
        </ul>
      </div>
    </div>
    <hr/>
    <div id="frame">
      <%= flash_tag(flash) %>

      <div id="content">
        <%= yield %>
      </div>
      <hr/>
      <div id="sidebar">
        <h2>PigeBox<sup>beta</sup></h2>

        <ul>
          <li><%= link_to t(".chunks.index"), source_chunks_path(Source.default) %></li>
          <li><%= link_to t("chunks.actions.create"), new_source_chunk_path(Source.default) %></li>
        </ul>

        <ul>
          <li><%= link_to t(".labels.index"), source_labels_path(Source.default) %></li>
          <li><%= link_to t(".labels.new"), new_source_label_path(Source.default) %></li>
        </ul>

        <ul>
          <li><%= link_to Network.model_name.human, networks_path %></li>
          <li><%= link_to Ssh.model_name.human, ssh_path %></li>
          <li><%= link_to Log.model_name.human, log_path %></li>
          <li><%= link_to SavePoint.model_name.human, new_save_point_path %></li>
          <li><%= link_to Box::Release.model_name.human, releases_path %></li>
        </ul>
        <h2><%= LabelSelection.model_name.human %></h2>

        <%= render user_session.label_selection %>

        <h2><%= t(".information.title") %></h2>
        <%= site_information_tag %>
        <p>
          <%= t(".information.text").html_safe %>
        </p>

        <p class="languages">
          <%= links_to_languages %>
        </p>
      </div>
    </div>
    <hr/>
    <div id="footer">
      <div>
        &nbsp;
      </div>
    </div>
  </body>
</html>